// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using si_td_gestion_eventos.Context;

#nullable disable

namespace si_td_gestion_eventos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008182211_primera")]
    partial class primera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaIdentidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Activo = true,
                            Apellido = "test",
                            CedulaIdentidad = "131331313",
                            Domicilio = "calle",
                            Nombre = "test",
                            Telefono = "47832"
                        });
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ComprobanteExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaComprobante")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("ComprobanteExterno");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoAireAcondicionado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoReserva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResponsableCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Fianza", b =>
                {
                    b.Property<int>("FianzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FianzaId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoDevuelto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FianzaId");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("Fianza");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("int");

                    b.Property<string>("ComprobanteRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComprobanteTipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ComprobanteExterno", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Pago", "Pago")
                        .WithOne("ComprobanteExterno")
                        .HasForeignKey("si_td_gestion_eventos.Entities.ComprobanteExterno", "PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Fianza", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithOne("Fianza")
                        .HasForeignKey("si_td_gestion_eventos.Entities.Fianza", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithMany("Pagos")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Cliente", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.Navigation("Fianza");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.Navigation("ComprobanteExterno");
                });
#pragma warning restore 612, 618
        }
    }
}
