// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using si_td_gestion_eventos.Context;

#nullable disable

namespace si_td_gestion_eventos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CedulaIdentidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RUT")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("CedulaIdentidad")
                        .IsUnique()
                        .HasFilter("[CedulaIdentidad] IS NOT NULL");

                    b.HasIndex("RUT")
                        .IsUnique()
                        .HasFilter("[RUT] IS NOT NULL");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Activo = true,
                            Apellido = "Perez",
                            CedulaIdentidad = "12345678",
                            Domicilio = "Calle Falsa",
                            Nombre = "Juan",
                            Telefono = "47832777",
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ComprobanteExterno", b =>
                {
                    b.Property<int>("ComprobanteExternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComprobanteExternoId"));

                    b.Property<DateTime>("FechaComprobante")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArchivo")
                        .HasColumnType("int");

                    b.HasKey("ComprobanteExternoId");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("ComprobanteExterno");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoAlquiler")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FianzaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoAireAcondicionado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoReserva")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Fianza", b =>
                {
                    b.Property<int>("FianzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FianzaId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoDevuelto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FianzaId");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("Fianza");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int?>("ComprobanteExternoId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valido")
                        .HasColumnType("bit");

                    b.HasKey("PagoId");

                    b.HasIndex("EventoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<float>("MontoAlquiler")
                        .HasColumnType("real");

                    b.Property<float>("MontoPagado")
                        .HasColumnType("real");

                    b.HasKey("ReporteId");

                    b.HasIndex("EventoId");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ServicioEsencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("ServiciosEsenciales");

                    b.HasDiscriminator<string>("TipoServicio").HasValue("ServicioEsencial");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.CertificadoAGADU", b =>
                {
                    b.HasBaseType("si_td_gestion_eventos.Entities.ServicioEsencial");

                    b.Property<DateTime?>("FechaAdjunto")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("AGADU");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ComprobanteExterno", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Pago", "Pago")
                        .WithOne("ComprobanteExterno")
                        .HasForeignKey("si_td_gestion_eventos.Entities.ComprobanteExterno", "PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("si_td_gestion_eventos.Entities.ResponsableSalon", "ResponsableSalon", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("int");

                            b1.Property<string>("CI")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EventoId");

                            b1.ToTable("Evento");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("ResponsableSalon")
                        .IsRequired();
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Fianza", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithOne("Fianza")
                        .HasForeignKey("si_td_gestion_eventos.Entities.Fianza", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithMany("Pagos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Reporte", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithMany("Reportes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.ServicioEsencial", b =>
                {
                    b.HasOne("si_td_gestion_eventos.Entities.Evento", "Evento")
                        .WithMany("ServiciosEsenciales")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Cliente", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Evento", b =>
                {
                    b.Navigation("Fianza");

                    b.Navigation("Pagos");

                    b.Navigation("Reportes");

                    b.Navigation("ServiciosEsenciales");
                });

            modelBuilder.Entity("si_td_gestion_eventos.Entities.Pago", b =>
                {
                    b.Navigation("ComprobanteExterno");
                });
#pragma warning restore 612, 618
        }
    }
}
